"use client";

import { MediaItem } from "@/lib/media";
import { useState, useMemo, useRef } from "react";
import Link from "next/link";
import { CurrentUser } from "@/lib/user";

interface YouTubeGridProps {
  items: MediaItem[];
  user: CurrentUser | null;
}

interface Filter {
  key: string;
  label: string;
  match: (item: MediaItem) => boolean;
}

/* Only filters that actually narrow the result set are listed. The
 * Music/Gaming/News/etc chips YouTube shows are mock data and would
 * need a real taxonomy + indexing to be useful, so they're omitted
 * until there's content behind them. */
const FILTERS: Filter[] = [
  { key: "all", label: "All", match: () => true },
  {
    key: "photos",
    label: "Photos",
    match: (i) => i.type === "photo",
  },
  {
    key: "videos",
    label: "Videos",
    match: (i) => i.type === "video",
  },
  {
    key: "gifs",
    label: "GIFs",
    match: (i) => i.type === "gif",
  },
  {
    key: "ai",
    label: "AI generated",
    match: (i) => i.isGenerated,
  },
];

/* Pseudo-random but stable channel for a media item — same input
 * always produces the same channel/avatar, like YouTube does for
 * its autogenerated content. */
function channelFor(name: string): { name: string; initial: string; color: string } {
  // Hash the name → 32-bit int, then split into an index and a colour shift.
  let h = 0;
  for (let i = 0; i < name.length; i++) {
    h = (h * 31 + name.charCodeAt(i)) | 0;
  }
  const palette = [
    "#e53935",
    "#1e88e5",
    "#43a047",
    "#fb8c00",
    "#8e24aa",
    "#00acc1",
    "#fdd835",
    "#6d4c41",
  ];
  const color = palette[Math.abs(h) % palette.length];
  const channels = [
    "Voyle Picks",
    "Auto Edit",
    "Daily Drop",
    "Archive",
    "Studio Voyle",
    "Highlights",
    "Untitled",
    "Memory Lane",
  ];
  return {
    name: channels[Math.abs(h >> 3) % channels.length],
    initial: channels[Math.abs(h >> 3) % channels.length]
      .split(/\s+/)
      .map((s) => s[0])
      .join("")
      .slice(0, 2)
      .toUpperCase(),
    color,
  };
}

/* Format a bytes-since-epoch-like view count into a short string. */
function formatViews(seed: number): string {
  const buckets = [
    "12K views",
    "48K views",
    "123K views",
    "1.2M views",
    "3.4M views",
    "812K views",
    "67K views",
    "2.1M views",
    "Recommended for you",
    "543 views",
    "5.7K views",
    "27K views",
    "99K views",
  ];
  return buckets[Math.abs(seed) % buckets.length];
}

function timeAgo(seed: number): string {
  const choices = [
    "3 hours ago",
    "1 day ago",
    "2 days ago",
    "1 week ago",
    "3 weeks ago",
    "1 month ago",
    "3 months ago",
    "6 months ago",
    "1 year ago",
    "2 years ago",
    "Streamed 2 days ago",
  ];
  return choices[Math.abs(seed) % choices.length];
}

export default function YouTubeGrid({
  items,
  user,
}: YouTubeGridProps) {
  const [filter, setFilter] = useState<string>("all");
  const [uploading, setUploading] = useState(false);
  const [uploadMsg, setUploadMsg] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const visible = useMemo(
    () => items.filter((f) => FILTERS.find((x) => x.key === filter)?.match(f) ?? true),
    [items, filter]
  );

  function handleUpload(e: React.ChangeEvent<HTMLInputElement>) {
    const files = e.target.files;
    if (!files || files.length === 0) return;
    setUploading(true);
    setUploadMsg(null);
    const fd = new FormData();
    for (let i = 0; i < files.length; i++) fd.append("files", files[i]);
    fetch("/api/media", { method: "POST", body: fd })
      .then((r) => r.json())
      .then((d) => {
        if (d.errors?.length) {
          setUploadMsg(d.errors.map((er: { error: string }) => er.error).join(", "));
        } else {
          setUploadMsg(`Uploaded ${d.saved?.length ?? 0} file(s)`);
          window.location.reload();
        }
      })
      .catch((err) => setUploadMsg(`Upload failed: ${err.message}`))
      .finally(() => {
        setUploading(false);
        if (fileInputRef.current) fileInputRef.current.value = "";
      });
  }

  return (
    <div className="space-y-4">
      {/* Filter chip row */}
      <div className="flex items-center gap-3">
        <div className="flex-1 min-w-0 overflow-x-auto scrollbar-thin">
          <div className="flex gap-2 w-max">
            {FILTERS.map((f) => (
              <button
                key={f.key}
                type="button"
                onClick={() => setFilter(f.key)}
                className={`yt-chip ${filter === f.key ? "yt-chip-active" : ""}`}
              >
                {f.label}
              </button>
            ))}
          </div>
        </div>
        {/* Upload icon button */}
        <input
          ref={fileInputRef}
          type="file"
          multiple
          accept="image/*,video/*,.gif,.mp4,.webm,.mov,.avi,.mkv,.m4v"
          onChange={handleUpload}
          className="hidden"
        />
        <button
          type="button"
          onClick={() => fileInputRef.current?.click()}
          disabled={uploading}
          className="yt-btn-icon flex-shrink-0"
          aria-label="Upload"
          title="Upload"
        >
          <svg viewBox="0 0 24 24" className="w-5 h-5" fill="currentColor">
            <path d="M14 13h-3v3H9v-3H6v-2h3V8h2v3h3v2zm7-6H3v12h18V7zm0-2c1.1 0 2 .9 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h18z" />
          </svg>
        </button>
      </div>

      {uploadMsg && (
        <p className="text-sm text-[color:var(--yt-text-secondary)]">
          {uploadMsg}
        </p>
      )}

      {/* Video grid — mirrors YouTube's 1/2/3/4/5 column responsive layout */}
      {visible.length === 0 ? (
        <p className="py-16 text-center text-[color:var(--yt-text-secondary)] text-sm">
          No items match this filter.
        </p>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-x-4 gap-y-8">
          {visible.map((item, i) => (
            <VideoCard key={item.id} item={item} seed={hashSeed(item.name) + i} />
          ))}
        </div>
      )}

      {/* Footer credit — small, optional */}
      {user && (
        <p className="pt-6 text-xs text-[color:var(--yt-text-secondary)]">
          Signed in as {user.name}. Tap any thumbnail to open the viewer.
        </p>
      )}
    </div>
  );
}

/* Stable per-name hash → a 32-bit int. */
function hashSeed(name: string): number {
  let h = 0;
  for (let i = 0; i < name.length; i++) {
    h = (h * 31 + name.charCodeAt(i)) | 0;
  }
  return h;
}

function VideoCard({ item, seed }: { item: MediaItem; seed: number }) {
  const channel = channelFor(item.name);
  const shareUrl = `/p/${encodeURIComponent(item.path)}`;

  return (
    <article className="group">
      {/* Thumbnail — 16:9 box */}
      <Link
        href={shareUrl}
        className="block relative aspect-video rounded-xl overflow-hidden bg-[color:var(--yt-chip)]"
      >
        {item.type === "video" ? (
          <video
            src={`/api/media/file/${item.path}`}
            muted
            playsInline
            preload="metadata"
            className="w-full h-full object-cover"
          />
        ) : (
          <img
            src={`/api/media/file/${item.path}`}
            alt={item.name}
            loading="lazy"
            className="w-full h-full object-cover transition-transform duration-200 group-hover:scale-[1.02]"
          />
        )}

        {/* Bottom-right duration badge (videos only) */}
        {item.type === "video" && (
          <span className="absolute bottom-1 right-1 px-1.5 py-0.5 bg-black/80 text-white text-xs font-medium rounded">
            VIDEO
          </span>
        )}
        {item.type === "gif" && (
          <span className="absolute bottom-1 right-1 px-1.5 py-0.5 bg-black/80 text-white text-xs font-medium rounded">
            GIF
          </span>
        )}
        {item.type === "photo" && item.isGenerated && (
          <span className="absolute bottom-1 right-1 px-1.5 py-0.5 bg-black/80 text-white text-xs font-medium rounded">
            AI
          </span>
        )}
      </Link>

      {/* Title + channel row */}
      <div className="flex gap-3 mt-3">
        <div
          className="flex-shrink-0 w-9 h-9 rounded-full flex items-center justify-center text-white text-xs font-medium"
          style={{ backgroundColor: channel.color }}
          aria-hidden
        >
          {channel.initial}
        </div>
        <div className="min-w-0 flex-1">
          <h3 className="text-sm font-medium leading-snug line-clamp-2 text-[color:var(--yt-text)]">
            <Link href={shareUrl} className="hover:text-[color:var(--yt-text)]">
              {prettyTitle(item.name)}
            </Link>
          </h3>
          <p className="mt-1 text-xs text-[color:var(--yt-text-secondary)] truncate">
            {channel.name}
          </p>
          <p className="text-xs text-[color:var(--yt-text-secondary)]">
            {formatViews(seed)} · {timeAgo(seed)}
          </p>
        </div>
      </div>
    </article>
  );
}

/* Strip the file extension and convert separator characters to spaces
 * for a more YouTube-style title. Keeps the original chars in the URL
 * via the underlying href. */
function prettyTitle(filename: string): string {
  const dot = filename.lastIndexOf(".");
  const stem = dot > 0 ? filename.slice(0, dot) : filename;
  // "image (1)" → "Image (1)"; "sunset_photo" → "Sunset Photo"
  return stem
    .replace(/[._-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/\b\w/g, (c) => c.toUpperCase());
}